version: '3.8'

services:
  app:
    image: barry4holly/car_price_app:a3
    platform: linux/amd64
    environment:
      - DEBUG=False  # Set DEBUG to False for production
    command: python manage.py runserver 0.0.0.0:80
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.app-st124956.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is app-st124956
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.app-st124956.rule=Host(`st124956.ml.brain.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.app-st124956.tls=true
      - traefik.http.routers.app-st124956.tls.certresolver=production
      - traefik.http.routers.app-st124956.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this
networks:
  default:
  traefik_default:
    external: true