version: '3.8'

services:
  app:
    image: barry4holly/car_price_app:a3
    platform: linux/amd64
    ports:
      - "8000:80"
    environment:
      - DEBUG=False  # Set DEBUG to False for production
    command: python manage.py runserver 0.0.0.0:80
